analyze -sva wrapper.v
elaborate -top wrapper
clock clk
reset rst
assume { noreset__m0__  }
assume { variable_map_assume__m4__  }
assume { variable_map_assume__m6__  }
assume { variable_map_assume__m10__  }
assume { variable_map_assume__m16__  }
assume { variable_map_assume__m21__  }
assume { variable_map_assume__m26__  }
assume { variable_map_assume__m29__  }
assume { variable_map_assume__m32__  }
assume { variable_map_assume__m37__  }
assume { variable_map_assume__m42__  }
assume { variable_map_assume__m47__  }
assume { variable_map_assume__m49__  }
assume { variable_map_assume__m51__  }
assume { variable_map_assume__m53__  }
assume { variable_map_assume__m56__  }
assume { variable_map_assume__m58__  }
assume { variable_map_assume__m63__  }
assume { variable_map_assume__m67__  }
assume { variable_map_assume__m71__  }
assume { variable_map_assume__m73__  }
assume { variable_map_assume__m75__  }
assume { variable_map_assume__m77__  }
assume { invariant_assume__m97__  }
assume { invariant_assume__m98__  }
assume { additional_mapping_control_assume__m99__  }
assume { additional_mapping_control_assume__m100__  }
assume { additional_mapping_control_assume__m101__  }
assume { additional_mapping_control_assume__m102__  }
assume { additional_mapping_control_assume__m103__  }
assume { additional_mapping_control_assume__m104__  }
assume { additional_mapping_control_assume__m105__  }
assume { additional_mapping_control_assume__m106__  }
assume { additional_mapping_control_assume__m107__  }
assume { additional_mapping_control_assume__m108__  }
assume { additional_mapping_control_assume__m109__  }
assume { additional_mapping_control_assume__m110__  }
assume { additional_mapping_control_assume__m111__  }
assume { issue_decode__m112__  }
assume { issue_valid__m113__  }
assume { post_value_holder__m114__  }
assume { post_value_holder__m115__  }
assume { post_value_holder__m116__  }
assume { post_value_holder__m117__  }
assume { post_value_holder__m118__  }
assume { post_value_holder__m119__  }
assume { post_value_holder__m120__  }
assume { post_value_holder__m121__  }
assume { post_value_holder__m122__  }
assume { post_value_holder__m123__  }
assume { post_value_holder__m124__  }
assume { post_value_holder__m125__  }
assume { post_value_holder__m126__  }
assume { post_value_holder__m127__  }
assume { post_value_holder__m128__  }
assume { post_value_holder__m129__  }
assume { post_value_holder__m130__  }
assume { post_value_holder__m131__  }
assume { post_value_holder__m132__  }
assume { post_value_holder__m133__  }
assume { post_value_holder__m134__  }
assume { post_value_holder__m135__  }
assume { post_value_holder__m136__  }
assume { post_value_holder__m137__  }
assume { post_value_holder__m138__  }
assert { (variable_map_assert__p85__ ) && (variable_map_assert__p90__ ) && (variable_map_assert__p92__ ) && (variable_map_assert__p94__ ) && (variable_map_assert__p96__ ) }
