analyze -sva wrapper.v
elaborate -top wrapper
clock clk
reset rst
assume { noreset__m0__  }
assume { variable_map_assume__m4__  }
assume { variable_map_assume__m6__  }
assume { variable_map_assume__m10__  }
assume { variable_map_assume__m16__  }
assume { variable_map_assume__m19__  }
assume { variable_map_assume__m22__  }
assume { variable_map_assume__m25__  }
assume { variable_map_assume__m28__  }
assume { variable_map_assume__m31__  }
assume { variable_map_assume__m36__  }
assume { variable_map_assume__m38__  }
assume { variable_map_assume__m40__  }
assume { variable_map_assume__m43__  }
assume { variable_map_assume__m45__  }
assume { variable_map_assume__m50__  }
assume { variable_map_assume__m54__  }
assume { variable_map_assume__m58__  }
assume { variable_map_assume__m60__  }
assume { variable_map_assume__m62__  }
assume { variable_map_assume__m64__  }
assume { invariant_assume__m79__  }
assume { invariant_assume__m80__  }
assume { additional_mapping_control_assume__m81__  }
assume { additional_mapping_control_assume__m82__  }
assume { additional_mapping_control_assume__m83__  }
assume { additional_mapping_control_assume__m84__  }
assume { additional_mapping_control_assume__m85__  }
assume { additional_mapping_control_assume__m86__  }
assume { additional_mapping_control_assume__m87__  }
assume { additional_mapping_control_assume__m88__  }
assume { additional_mapping_control_assume__m89__  }
assume { additional_mapping_control_assume__m90__  }
assume { additional_mapping_control_assume__m91__  }
assume { issue_decode__m92__  }
assume { issue_valid__m93__  }
assume { post_value_holder__m94__  }
assume { post_value_holder__m95__  }
assume { post_value_holder__m96__  }
assume { post_value_holder__m97__  }
assume { post_value_holder__m98__  }
assume { post_value_holder__m99__  }
assume { post_value_holder__m100__  }
assume { post_value_holder__m101__  }
assume { post_value_holder__m102__  }
assume { post_value_holder__m103__  }
assume { post_value_holder__m104__  }
assume { post_value_holder__m105__  }
assume { post_value_holder__m106__  }
assume { post_value_holder__m107__  }
assume { post_value_holder__m108__  }
assume { post_value_holder__m109__  }
assume { post_value_holder__m110__  }
assume { post_value_holder__m111__  }
assume { post_value_holder__m112__  }
assume { post_value_holder__m113__  }
assert { (variable_map_assert__p74__ ) && (variable_map_assert__p76__ ) && (variable_map_assert__p78__ ) }
