analyze -sva wrapper.v
elaborate -top wrapper
clock clk
reset rst
assume { noreset__m0__  }
assume { variable_map_assume__m2__  }
assume { variable_map_assume__m4__  }
assume { variable_map_assume__m6__  }
assume { variable_map_assume__m8__  }
assume { variable_map_assume__m13__  }
assume { variable_map_assume__m18__  }
assume { variable_map_assume__m21__  }
assume { variable_map_assume__m24__  }
assume { variable_map_assume__m29__  }
assume { variable_map_assume__m31__  }
assume { variable_map_assume__m36__  }
assume { variable_map_assume__m38__  }
assume { variable_map_assume__m40__  }
assume { variable_map_assume__m42__  }
assume { variable_map_assume__m45__  }
assume { variable_map_assume__m47__  }
assume { variable_map_assume__m52__  }
assume { variable_map_assume__m56__  }
assume { variable_map_assume__m60__  }
assume { variable_map_assume__m62__  }
assume { variable_map_assume__m64__  }
assume { variable_map_assume__m66__  }
assume { invariant_assume__m82__  }
assume { invariant_assume__m83__  }
assume { invariant_assume__m84__  }
assume { invariant_assume__m85__  }
assume { invariant_assume__m86__  }
assume { invariant_assume__m87__  }
assume { invariant_assume__m88__  }
assume { invariant_assume__m89__  }
assume { invariant_assume__m90__  }
assume { invariant_assume__m91__  }
assume { invariant_assume__m92__  }
assume { invariant_assume__m93__  }
assume { invariant_assume__m94__  }
assume { invariant_assume__m95__  }
assume { invariant_assume__m96__  }
assume { invariant_assume__m97__  }
assume { invariant_assume__m98__  }
assume { invariant_assume__m99__  }
assume { invariant_assume__m100__  }
assume { invariant_assume__m101__  }
assume { invariant_assume__m102__  }
assume { invariant_assume__m103__  }
assume { invariant_assume__m104__  }
assume { additional_mapping_control_assume__m105__  }
assume { additional_mapping_control_assume__m106__  }
assume { additional_mapping_control_assume__m107__  }
assume { additional_mapping_control_assume__m108__  }
assume { additional_mapping_control_assume__m109__  }
assume { additional_mapping_control_assume__m110__  }
assume { additional_mapping_control_assume__m111__  }
assume { additional_mapping_control_assume__m112__  }
assume { additional_mapping_control_assume__m113__  }
assume { additional_mapping_control_assume__m114__  }
assume { additional_mapping_control_assume__m115__  }
assume { additional_mapping_control_assume__m116__  }
assume { issue_decode__m117__  }
assume { issue_valid__m118__  }
assume { post_value_holder__m119__  }
assume { post_value_holder__m120__  }
assume { post_value_holder__m121__  }
assume { post_value_holder__m122__  }
assume { post_value_holder__m123__  }
assume { post_value_holder__m124__  }
assume { post_value_holder__m125__  }
assume { post_value_holder__m126__  }
assume { post_value_holder__m127__  }
assume { post_value_holder__m128__  }
assume { post_value_holder__m129__  }
assume { post_value_holder__m130__  }
assume { post_value_holder__m131__  }
assume { post_value_holder__m132__  }
assume { post_value_holder__m133__  }
assume { post_value_holder__m134__  }
assume { post_value_holder__m135__  }
assume { post_value_holder__m136__  }
assume { post_value_holder__m137__  }
assume { post_value_holder__m138__  }
assume { post_value_holder__m139__  }
assume { post_value_holder__m140__  }
assume { post_value_holder__m141__  }
assume { post_value_holder__m142__  }
assume { post_value_holder__m143__  }
assert { (variable_map_assert__p70__ ) && (variable_map_assert__p75__ ) && (variable_map_assert__p77__ ) && (variable_map_assert__p79__ ) && (variable_map_assert__p81__ ) }
