analyze -sva wrapper.v
elaborate -top wrapper
clock clk
reset rst
assume { noreset__m0__  }
assume { variable_map_assume__m4__  }
assume { variable_map_assume__m6__  }
assume { variable_map_assume__m10__  }
assume { variable_map_assume__m16__  }
assume { variable_map_assume__m19__  }
assume { variable_map_assume__m22__  }
assume { variable_map_assume__m25__  }
assume { variable_map_assume__m28__  }
assume { variable_map_assume__m31__  }
assume { variable_map_assume__m36__  }
assume { variable_map_assume__m38__  }
assume { variable_map_assume__m40__  }
assume { variable_map_assume__m43__  }
assume { variable_map_assume__m45__  }
assume { variable_map_assume__m50__  }
assume { variable_map_assume__m54__  }
assume { variable_map_assume__m58__  }
assume { variable_map_assume__m60__  }
assume { variable_map_assume__m62__  }
assume { variable_map_assume__m64__  }
assume { invariant_assume__m114__  }
assume { invariant_assume__m115__  }
assume { additional_mapping_control_assume__m116__  }
assume { additional_mapping_control_assume__m117__  }
assume { additional_mapping_control_assume__m118__  }
assume { additional_mapping_control_assume__m119__  }
assume { additional_mapping_control_assume__m120__  }
assume { additional_mapping_control_assume__m121__  }
assume { additional_mapping_control_assume__m122__  }
assume { additional_mapping_control_assume__m123__  }
assume { additional_mapping_control_assume__m124__  }
assume { additional_mapping_control_assume__m125__  }
assume { additional_mapping_control_assume__m126__  }
assume { issue_decode__m127__  }
assume { issue_valid__m128__  }
assume { post_value_holder__m129__  }
assume { post_value_holder__m130__  }
assume { post_value_holder__m131__  }
assume { post_value_holder__m132__  }
assume { post_value_holder__m133__  }
assume { post_value_holder__m134__  }
assume { post_value_holder__m135__  }
assume { post_value_holder__m136__  }
assume { post_value_holder__m137__  }
assume { post_value_holder__m138__  }
assume { post_value_holder__m139__  }
assume { post_value_holder__m140__  }
assume { post_value_holder__m141__  }
assume { post_value_holder__m142__  }
assume { post_value_holder__m143__  }
assume { post_value_holder__m144__  }
assume { post_value_holder__m145__  }
assume { post_value_holder__m146__  }
assume { post_value_holder__m147__  }
assume { post_value_holder__m148__  }
assert { (variable_map_assert__p68__ ) && (variable_map_assert__p72__ ) && (variable_map_assert__p80__ ) && (variable_map_assert__p83__ ) && (variable_map_assert__p86__ ) && (variable_map_assert__p91__ ) && (variable_map_assert__p94__ ) && (variable_map_assert__p99__ ) && (variable_map_assert__p103__ ) && (variable_map_assert__p107__ ) && (variable_map_assert__p109__ ) && (variable_map_assert__p111__ ) && (variable_map_assert__p113__ ) }
