analyze -sva wrapper.v
elaborate -top wrapper
clock clk
reset rst
assume { noreset__m0__  }
assume { variable_map_assume__m4__  }
assume { variable_map_assume__m6__  }
assume { variable_map_assume__m10__  }
assume { variable_map_assume__m16__  }
assume { variable_map_assume__m21__  }
assume { variable_map_assume__m26__  }
assume { variable_map_assume__m29__  }
assume { variable_map_assume__m32__  }
assume { variable_map_assume__m37__  }
assume { variable_map_assume__m42__  }
assume { variable_map_assume__m47__  }
assume { variable_map_assume__m49__  }
assume { variable_map_assume__m51__  }
assume { variable_map_assume__m53__  }
assume { variable_map_assume__m56__  }
assume { variable_map_assume__m58__  }
assume { variable_map_assume__m63__  }
assume { variable_map_assume__m67__  }
assume { variable_map_assume__m71__  }
assume { variable_map_assume__m73__  }
assume { variable_map_assume__m75__  }
assume { variable_map_assume__m77__  }
assume { invariant_assume__m132__  }
assume { invariant_assume__m133__  }
assume { additional_mapping_control_assume__m134__  }
assume { additional_mapping_control_assume__m135__  }
assume { additional_mapping_control_assume__m136__  }
assume { additional_mapping_control_assume__m137__  }
assume { additional_mapping_control_assume__m138__  }
assume { additional_mapping_control_assume__m139__  }
assume { additional_mapping_control_assume__m140__  }
assume { additional_mapping_control_assume__m141__  }
assume { additional_mapping_control_assume__m142__  }
assume { additional_mapping_control_assume__m143__  }
assume { additional_mapping_control_assume__m144__  }
assume { additional_mapping_control_assume__m145__  }
assume { additional_mapping_control_assume__m146__  }
assume { issue_decode__m147__  }
assume { issue_valid__m148__  }
assume { post_value_holder__m149__  }
assume { post_value_holder__m150__  }
assume { post_value_holder__m151__  }
assume { post_value_holder__m152__  }
assume { post_value_holder__m153__  }
assume { post_value_holder__m154__  }
assume { post_value_holder__m155__  }
assume { post_value_holder__m156__  }
assume { post_value_holder__m157__  }
assume { post_value_holder__m158__  }
assume { post_value_holder__m159__  }
assume { post_value_holder__m160__  }
assume { post_value_holder__m161__  }
assume { post_value_holder__m162__  }
assume { post_value_holder__m163__  }
assume { post_value_holder__m164__  }
assume { post_value_holder__m165__  }
assume { post_value_holder__m166__  }
assume { post_value_holder__m167__  }
assume { post_value_holder__m168__  }
assume { post_value_holder__m169__  }
assume { post_value_holder__m170__  }
assume { post_value_holder__m171__  }
assume { post_value_holder__m172__  }
assume { post_value_holder__m173__  }
assert { (variable_map_assert__p81__ ) && (variable_map_assert__p83__ ) && (variable_map_assert__p87__ ) && (variable_map_assert__p97__ ) && (variable_map_assert__p102__ ) && (variable_map_assert__p107__ ) && (variable_map_assert__p112__ ) && (variable_map_assert__p114__ ) && (variable_map_assert__p119__ ) && (variable_map_assert__p123__ ) && (variable_map_assert__p127__ ) && (variable_map_assert__p129__ ) && (variable_map_assert__p131__ ) }
