analyze -sva wrapper.v
elaborate -top wrapper
clock clk
reset rst
assume { noreset__m0__  }
assume { variable_map_assume__m2__  }
assume { variable_map_assume__m4__  }
assume { variable_map_assume__m6__  }
assume { variable_map_assume__m8__  }
assume { variable_map_assume__m13__  }
assume { variable_map_assume__m18__  }
assume { variable_map_assume__m21__  }
assume { variable_map_assume__m24__  }
assume { variable_map_assume__m29__  }
assume { variable_map_assume__m31__  }
assume { variable_map_assume__m36__  }
assume { variable_map_assume__m38__  }
assume { variable_map_assume__m40__  }
assume { variable_map_assume__m42__  }
assume { variable_map_assume__m45__  }
assume { variable_map_assume__m47__  }
assume { variable_map_assume__m52__  }
assume { variable_map_assume__m56__  }
assume { variable_map_assume__m60__  }
assume { variable_map_assume__m62__  }
assume { variable_map_assume__m64__  }
assume { variable_map_assume__m66__  }
assume { invariant_assume__m110__  }
assume { invariant_assume__m111__  }
assume { invariant_assume__m112__  }
assume { invariant_assume__m113__  }
assume { invariant_assume__m114__  }
assume { invariant_assume__m115__  }
assume { invariant_assume__m116__  }
assume { invariant_assume__m117__  }
assume { invariant_assume__m118__  }
assume { invariant_assume__m119__  }
assume { invariant_assume__m120__  }
assume { invariant_assume__m121__  }
assume { invariant_assume__m122__  }
assume { invariant_assume__m123__  }
assume { invariant_assume__m124__  }
assume { invariant_assume__m125__  }
assume { invariant_assume__m126__  }
assume { invariant_assume__m127__  }
assume { invariant_assume__m128__  }
assume { invariant_assume__m129__  }
assume { invariant_assume__m130__  }
assume { invariant_assume__m131__  }
assume { invariant_assume__m132__  }
assume { additional_mapping_control_assume__m133__  }
assume { additional_mapping_control_assume__m134__  }
assume { additional_mapping_control_assume__m135__  }
assume { additional_mapping_control_assume__m136__  }
assume { additional_mapping_control_assume__m137__  }
assume { additional_mapping_control_assume__m138__  }
assume { additional_mapping_control_assume__m139__  }
assume { additional_mapping_control_assume__m140__  }
assume { additional_mapping_control_assume__m141__  }
assume { additional_mapping_control_assume__m142__  }
assume { additional_mapping_control_assume__m143__  }
assume { additional_mapping_control_assume__m144__  }
assume { issue_decode__m145__  }
assume { issue_valid__m146__  }
assume { post_value_holder__m147__  }
assume { post_value_holder__m148__  }
assume { post_value_holder__m149__  }
assume { post_value_holder__m150__  }
assume { post_value_holder__m151__  }
assume { post_value_holder__m152__  }
assume { post_value_holder__m153__  }
assume { post_value_holder__m154__  }
assume { post_value_holder__m155__  }
assume { post_value_holder__m156__  }
assume { post_value_holder__m157__  }
assume { post_value_holder__m158__  }
assume { post_value_holder__m159__  }
assume { post_value_holder__m160__  }
assume { post_value_holder__m161__  }
assume { post_value_holder__m162__  }
assume { post_value_holder__m163__  }
assume { post_value_holder__m164__  }
assume { post_value_holder__m165__  }
assume { post_value_holder__m166__  }
assume { post_value_holder__m167__  }
assume { post_value_holder__m168__  }
assume { post_value_holder__m169__  }
assume { post_value_holder__m170__  }
assume { post_value_holder__m171__  }
assert { (variable_map_assert__p68__ ) && (variable_map_assert__p70__ ) && (variable_map_assert__p72__ ) && (variable_map_assert__p78__ ) && (variable_map_assert__p83__ ) && (variable_map_assert__p85__ ) && (variable_map_assert__p90__ ) && (variable_map_assert__p92__ ) && (variable_map_assert__p97__ ) && (variable_map_assert__p101__ ) && (variable_map_assert__p105__ ) && (variable_map_assert__p107__ ) && (variable_map_assert__p109__ ) }
